# Generated by Django 4.2.1 on 2023-06-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaGamificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('calorias_consumidas', models.FloatField()),
                ('meta_cumprida', models.BooleanField(default=True)),
            ],
        ),
    ]
