# Generated by Django 4.2.1 on 2023-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGamificada', '0002_metagamificada_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metagamificada',
            old_name='calorias_consumidas',
            new_name='qtd_carboidratos',
        ),
        migrations.AddField(
            model_name='metagamificada',
            name='qtd_gorduras',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metagamificada',
            name='qtd_proteinas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
