# Generated by Django 4.2.1 on 2023-06-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGamificada', '0003_rename_calorias_consumidas_metagamificada_qtd_carboidratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metagamificada',
            name='calorias_consumidas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
