# Generated by Django 4.2.1 on 2023-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMetrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetric',
            name='imc',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermetric',
            name='tmb',
            field=models.FloatField(blank=True),
        ),
    ]
