# Generated by Django 4.2.1 on 2023-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('qtd_calorias', models.FloatField()),
                ('qtd_carboidratos', models.FloatField()),
                ('qtd_gorduras', models.FloatField()),
                ('qtd_proteinas', models.FloatField()),
            ],
        ),
    ]
