# Generated by Django 4.2.1 on 2023-05-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='qtd_gorduras',
            new_name='qtd_gordura',
        ),
    ]
