# Generated by Django 4.2.1 on 2023-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_qtd_gorduras_alimento_qtd_gordura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='qtd_gordura',
            new_name='qtd_gorduras',
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
