# Generated by Django 4.2.1 on 2023-05-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='e_padrao',
            field=models.BooleanField(default=True),
        ),
    ]
