# Generated by Django 4.2.1 on 2023-05-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos', '0002_alter_alimento_e_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='e_padrao',
            field=models.BooleanField(default=False),
        ),
    ]
