# Generated by Django 4.2.1 on 2023-06-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos', '0003_alter_alimento_e_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
