# Generated by Django 4.2.1 on 2023-06-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos', '0004_alter_alimento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
