# Generated by Django 4.2.1 on 2023-06-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos', '0006_alter_alimento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='porcao',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
