# Generated by Django 4.2.1 on 2023-06-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcao', models.FloatField(default=0)),
                ('calorias_total', models.FloatField(default=0)),
                ('carboidratos_total', models.FloatField(default=0)),
                ('gorduras_total', models.FloatField(default=0)),
                ('proteinas_total', models.FloatField(default=0)),
            ],
        ),
    ]
