# Generated by Django 4.2.1 on 2023-06-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consumo', '0001_initial'),
        ('MetaDiaria', '0004_rename_ultima_seq_dias_metadiaria_seq_dias_anterior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Refeicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='consumidos_list',
            field=models.ManyToManyField(related_name='consumos', to='Refeicao.refeicao'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='meta_diaria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MetaDiaria.metadiaria'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
