# Generated by Django 4.2.1 on 2023-06-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumo', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumo',
            old_name='meta_diaria',
            new_name='meta_diaria_id',
        ),
    ]
