# Generated by Django 4.2.1 on 2023-06-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaDiaria', '0002_metadiaria_dias_consec_na_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadiaria',
            old_name='dias_consec_na_meta',
            new_name='seq_dias_atual',
        ),
        migrations.AddField(
            model_name='metadiaria',
            name='ultima_seq_dias',
            field=models.IntegerField(default=0),
        ),
    ]
